name: Main

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  build_test_release:
    name: 'On Main Push - Build, Test, Release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Use Node.js 20.17.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - run: bun install
        # `bun run test` produces the build
        # because the tests need access to the binary (see package.json)
      - run: bun run test
      - run: bunx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
