name: Main

on:
  push:
    branches:
      - main

jobs:
  build_test_release:
    name: 'On Main Push - Build, Test, Release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run test
      - run: bun run build
      # - run: bunx semantic-release
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
